# port
server:
  port: 8880

# datasource
spring:
  datasource:
    url: jdbc:mysql://ssssv111.mysql.cn-chengdu.rds.aliyuncs.com/wiki
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  # Redis
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    port: 6379
    password: 
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hjc.mapper

# log
logging:
  level:
    com:
      hjc:
        mapper: trace

