# port
server:
  port: 8880

# datasource
spring:
  datasource:
    url: jdbc:mysql://ssssv111.mysql.cn-chengdu.rds.aliyuncs.com/wiki
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hjc
    password: Ssssv123
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hjc.mapper