# port
server:
  port: 8880

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hjc.mapper

# log
logging:
  level:
    com:
      hjc:
        mapper: trace

# datasource
spring:
  config:
    import: application-secrets.yaml
